// File generated by `flutter pub get`, modifying "pubspec.yaml".
// This file should be version controlled and should not be manually edited.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb, defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKSHBNBICPHZ7LQKF_FXBoC_alGaIv-eQ',
    appId: '1:530115073074:web:6439fa42c2f6632c70182b',
    messagingSenderId: '530115073074',
    projectId: 'rentease-b242f',
    authDomain: 'rentease-b242f.firebaseapp.com',
    storageBucket: 'rentease-b242f.firebasestorage.app',
    measurementId: 'G-LPLJTS7EMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHHEqZYF4wLv4Hvs2AiXyXp4rdqdjCc9s',
    appId: '1:530115073074:android:b3b08d297aab8e1470182b',
    messagingSenderId: '530115073074',
    projectId: 'rentease-b242f',
    storageBucket: 'rentease-b242f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'rentease-xxxxx',
    databaseURL: 'https://rentease-xxxxx.firebaseio.com',
    storageBucket: 'rentease-xxxxx.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'rentease-xxxxx',
    databaseURL: 'https://rentease-xxxxx.firebaseio.com',
    storageBucket: 'rentease-xxxxx.appspot.com',
  );
}